# Preencha quando/se desejar habilitar sponsorship.
# Veja: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
# github: [soucheff]
